# Generated by Django 3.0.5 on 2020-10-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
