# Generated by Django 3.0.5 on 2020-10-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
